version: "latest"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: 1234
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"